### ISSUE TITLE
Readiness checklist

### ISSUE THREAD

**Issue by sentinelweb** [TechForUK/simple-vote-api#2]
**functionality**
- [ ] setup express server
- [ ] basic form population
    - [ ] UK voter registration
    - [ ] EU voter registration
    - [ ] Postal vote registration
- [ ] Email PDFs
- [ ] 

**Hosting**
- [ ] deployment (NodeJs environment)
- [ ] subdomain setup on get voting (separate subdomain to UI)
- [ ] SSL (should be ok as we will use get voting?)

**Other**
- [ ] Readme (environment variables, build and deployment instructions)
